import path from 'node:path';

import type { Clip, PreparedClip } from '../../shared/types.js';

function safeKey(name: string): string {
  const base = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  const withPrefix = base && /^[a-z_]/.test(base) ? base : `clip_${base || 'unnamed'}`;
  return withPrefix.slice(0, 60);
}

export function buildStrudelHelperSource({
  preparedClips,
  clipsById,
  exportDir,
}: {
  preparedClips: PreparedClip[];
  clipsById: Map<string, Clip>;
  exportDir: string;
}): string {
  const entries: Array<{ key: string; file: string; isLoop: boolean }> = [];

  for (const pc of preparedClips) {
    const clip = clipsById.get(pc.clipId);
    if (!clip) continue;
    const key = safeKey(clip.name);
    const file = `./${path.basename(pc.path)}`;
    entries.push({ key, file, isLoop: clip.isLoop });
  }

  entries.sort((a, b) => a.key.localeCompare(b.key));

  const clipsObj = entries
    .map((e) => `  ${JSON.stringify(e.key)}: ${JSON.stringify(e.file)},`)
    .join('\n');

  const loops = entries
    .filter((e) => e.isLoop)
    .map((e) => JSON.stringify(e.key))
    .join(', ');

  const oneShots = entries
    .filter((e) => !e.isLoop)
    .map((e) => JSON.stringify(e.key))
    .join(', ');

  return `// Generated by Loop Library\n// Export dir: ${exportDir}\n\nexport const clips = {\n${clipsObj}\n};\n\nexport const loopClips = [${loops}];\nexport const oneShotClips = [${oneShots}];\n`;
}
